import type { Exercise, PlanSnapshot } from "@/lib/types";

export const exercises: Exercise[] = [
  {
    id: "ex-goblet-squat",
    key: "goblet-squat",
    name: "Kurzhantel-Goblet-Squat",
    shortName: "Goblet Squat",
    dumbbellCount: 1,
    equipment: "Kurzhantel",
    demoSlug: "goblet-squat",
    cues: ["Brust stolz, Hantel nah am Körper", "Knie folgen den Fußspitzen", "Kontrolliert tief und kraftvoll hoch"],
  },
  {
    id: "ex-incline-bench",
    key: "incline-bench-press",
    name: "Schrägbankdrücken mit Kurzhanteln",
    shortName: "Schrägbank",
    dumbbellCount: 2,
    equipment: "Kurzhantel",
    demoSlug: "incline-bench-press",
    cues: ["Schulterblätter zur Bank ziehen", "Unterarme bleiben senkrecht", "Hanteln kontrolliert zur Brust führen"],
  },
  {
    id: "ex-flat-bench",
    key: "flat-bench-press",
    name: "Flachbankdrücken mit Kurzhanteln",
    shortName: "Flachbank",
    dumbbellCount: 2,
    equipment: "Kurzhantel",
    demoSlug: "flat-bench-press",
    cues: ["Füße fest am Boden", "Schulterblätter stabil halten", "Hanteln gleichmäßig hochdrücken"],
  },
  {
    id: "ex-bent-row",
    key: "bent-over-row",
    name: "Vorgebeugtes Kurzhantel-Rudern",
    shortName: "Rudern",
    dumbbellCount: 2,
    equipment: "Kurzhantel",
    demoSlug: "bent-over-row",
    cues: ["Rücken neutral, Hüfte nach hinten", "Ellbogen eng nach hinten führen", "Oberkörper bleibt ruhig"],
  },
  {
    id: "ex-shoulder-press",
    key: "seated-shoulder-press",
    name: "Schulterdrücken im Sitzen",
    shortName: "Schulterdrücken",
    dumbbellCount: 2,
    equipment: "Kurzhantel",
    demoSlug: "seated-shoulder-press",
    cues: ["Rücken anlehnen und Rumpf fest", "Handgelenke über den Ellbogen", "Nicht ins Hohlkreuz ausweichen"],
  },
  {
    id: "ex-curl",
    key: "dumbbell-curl",
    name: "Kurzhantel-Curls",
    shortName: "Curls",
    dumbbellCount: 2,
    equipment: "Kurzhantel",
    demoSlug: "dumbbell-curl",
    cues: ["Ellbogen bleiben am Körper", "Ohne Schwung anheben", "Langsam vollständig absenken"],
  },
  {
    id: "ex-hammer-curl",
    key: "hammer-curl",
    name: "Hammer-Curls",
    shortName: "Hammer-Curls",
    dumbbellCount: 2,
    equipment: "Kurzhantel",
    demoSlug: "hammer-curl",
    cues: ["Handflächen zeigen zueinander", "Ellbogen bleiben ruhig", "Beide Richtungen kontrollieren"],
  },
  {
    id: "ex-triceps",
    key: "overhead-triceps-extension",
    name: "Trizepsdrücken über Kopf",
    shortName: "Trizeps",
    dumbbellCount: 1,
    equipment: "Kurzhantel",
    demoSlug: "overhead-triceps-extension",
    cues: ["Eine Hantel sicher mit beiden Händen", "Ellbogen zeigen nach vorn", "Nur die Unterarme bewegen"],
  },
  {
    id: "ex-lateral-raise",
    key: "lateral-raise",
    name: "Seitheben im Stehen",
    shortName: "Seitheben",
    dumbbellCount: 2,
    equipment: "Kurzhantel",
    demoSlug: "lateral-raise",
    cues: ["Leicht gebeugte Ellbogen", "Bis ungefähr Schulterhöhe", "Keinen Schwung aus den Beinen"],
  },
  {
    id: "ex-leg-raise",
    key: "lying-leg-raise",
    name: "Beinheben im Liegen",
    shortName: "Beinheben",
    dumbbellCount: 0,
    equipment: "Körpergewicht",
    demoSlug: "lying-leg-raise",
    cues: ["Unteren Rücken am Boden halten", "Beine kontrolliert heben", "Vor dem Ablegen wieder umkehren"],
  },
];

export const initialPlan: PlanSnapshot = {
  name: "Trainingsplan Sommer 2027",
  goal: "Massiver Aufbau · ca. 80 kg definiert",
  exercises: [
    { slotId: "slot-squat", exerciseKeys: ["goblet-squat"], variantMode: "fixed", weightGrams: 17_500, sets: [{ reps: 10 }, { reps: 10 }, { reps: 10 }] },
    { slotId: "slot-bench", exerciseKeys: ["incline-bench-press", "flat-bench-press"], variantMode: "alternate", weightGrams: 10_000, sets: [{ reps: 12 }, { reps: 12 }, { reps: 12 }] },
    { slotId: "slot-row", exerciseKeys: ["bent-over-row"], variantMode: "fixed", weightGrams: 10_000, sets: [{ reps: 12 }, { reps: 12 }, { reps: 12 }] },
    { slotId: "slot-shoulder", exerciseKeys: ["seated-shoulder-press"], variantMode: "fixed", weightGrams: 10_000, sets: [{ reps: 10 }, { reps: 10 }, { reps: 8 }] },
    { slotId: "slot-curl", exerciseKeys: ["dumbbell-curl", "hammer-curl"], variantMode: "alternate", weightGrams: 10_000, sets: [{ reps: 10 }, { reps: 10 }, { reps: 7 }] },
    { slotId: "slot-triceps", exerciseKeys: ["overhead-triceps-extension"], variantMode: "fixed", weightGrams: 10_000, sets: [{ reps: 10 }, { reps: 10 }, { reps: 10 }] },
    { slotId: "slot-lateral", exerciseKeys: ["lateral-raise"], variantMode: "fixed", weightGrams: 2_500, sets: [{ reps: 12 }, { reps: 12 }, { reps: 12 }] },
    { slotId: "slot-leg-raise", exerciseKeys: ["lying-leg-raise"], variantMode: "fixed", weightGrams: 0, sets: [{ reps: 15 }, { reps: 15 }, { reps: 15 }] },
  ],
};

export const exerciseMap = new Map(exercises.map((exercise) => [exercise.key, exercise]));
